name: Build Docker Image

on:
  push:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag open-pdf-print-service .

      - name: Verify image was built
        run: docker images | grep open-pdf-print-service
